# Generated by Django 4.1.1 on 2022-09-21 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER_KIND_CODE',
            fields=[
                ('kind_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('kind_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=20)),
                ('user_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_kind_code')),
            ],
        ),
    ]
