# Generated by Django 4.1.1 on 2022-09-23 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_kind_code',
            fields=[
                ('kind_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('kind_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=20)),
                ('gender', models.IntegerField(default=0)),
                ('birth', models.DateTimeField(blank=True, null=True)),
                ('user_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_kind_code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
