# Generated by Django 4.1.1 on 2022-09-21 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_birth_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 21, 14, 43, 54, 242084)),
        ),
    ]
