# Generated by Django 4.1.1 on 2022-09-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='user_kind_code',
            table='user_kind_code',
        ),
    ]
