# Generated by Django 4.1.1 on 2022-09-25 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_kind',
            field=models.ForeignKey(db_column='user_kind', on_delete=django.db.models.deletion.CASCADE, to='user.user_kind_code'),
        ),
    ]
