# Generated by Django 4.1.1 on 2022-09-25 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_remove_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user', unique=True)),
                ('reply_list', models.CharField(max_length=8)),
            ],
        ),
    ]
