# Generated by Django 4.1.1 on 2022-09-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_survey_user_no'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='survey',
            table='survey',
        ),
    ]
