# Generated by Django 4.1.1 on 2022-09-25 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_last_login'),
        ('survey', '0003_alter_survey_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='user_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user'),
        ),
    ]
