# Generated by Django 4.1.1 on 2022-09-25 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_user_kind'),
        ('survey', '0004_alter_survey_user_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='user_no',
            field=models.OneToOneField(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user'),
        ),
    ]
