# Generated by Django 4.1.1 on 2022-09-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_survey_user_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='reply_list',
            field=models.JSONField(),
        ),
    ]
