# Generated by Django 4.1.1 on 2022-09-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0002_user_alcohol"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User_alcohol",
        ),
    ]
