# Generated by Django 4.1.1 on 2022-09-30 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_user_user_kind"),
        ("alcohol", "0015_alter_alcohol_recommend_alcohol_no"),
        ("mypage", "0003_delete_user_alcohol"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_alcohol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.SmallIntegerField()),
                (
                    "alcohol_no",
                    models.ForeignKey(
                        db_column="alcohol_no",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alcohol.alcohol",
                    ),
                ),
                (
                    "user_no",
                    models.ForeignKey(
                        db_column="user_no",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_alcohol",
            },
        ),
    ]
