# Generated by Django 4.1.1 on 2022-09-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0008_alter_user_user_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol_code',
            fields=[
                ('alcohol_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('alcohol_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'alcohol_code',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('alcohol_no', models.IntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': 'ranking',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_no', models.AutoField(primary_key=True, serialize=False)),
                ('alcohol_no', models.IntegerField()),
                ('score', models.IntegerField()),
                ('comment', models.CharField(max_length=150)),
                ('sweet', models.IntegerField()),
                ('sour', models.IntegerField()),
                ('scent', models.IntegerField()),
                ('body', models.IntegerField()),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
