# Generated by Django 4.1.1 on 2022-09-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wouldU', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='rank',
            new_name='ranking',
        ),
    ]
