# Generated by Django 4.1.1 on 2022-09-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wouldU', '0002_rename_rank_ranking_ranking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alcohol_code',
        ),
    ]
