# Generated by Django 4.1.1 on 2022-09-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0014_alter_alcohol_like_count'),
        ('wouldU', '0003_delete_alcohol_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='alcohol_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='alcohol.alcohol'),
        ),
        migrations.AlterField(
            model_name='review',
            name='alcohol_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcohol.alcohol'),
        ),
    ]
