# Generated by Django 4.1.1 on 2022-09-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wouldU', '0005_alter_ranking_alcohol_no_alter_review_alcohol_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
