# Generated by Django 4.1.1 on 2022-10-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_user_kind'),
        ('wouldU', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_kind',
            field=models.OneToOneField(db_column='user_kind', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user_kind_code'),
        ),
    ]
