# Generated by Django 4.1.1 on 2022-10-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wouldU', '0008_review_user_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_kind',
        ),
    ]
