# Generated by Django 4.1.1 on 2022-09-26 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alcol_code',
            fields=[
                ('alco_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('alco_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'alcol_code',
            },
        ),
        migrations.CreateModel(
            name='Region_code',
            fields=[
                ('region_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'region_code',
            },
        ),
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('alco_no', models.AutoField(primary_key=True, serialize=False)),
                ('alco_name', models.CharField(max_length=50)),
                ('alco_img', models.CharField(max_length=100)),
                ('abv', models.FloatField()),
                ('material', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('brewery', models.CharField(max_length=50, null=True)),
                ('award', models.CharField(max_length=100, null=True)),
                ('like_cnt', models.IntegerField(default=0, null=True)),
                ('food', models.CharField(max_length=100, null=True)),
                ('tags', models.JSONField(null=True)),
                ('alco_code', models.ForeignKey(db_column='alco_code', on_delete=django.db.models.deletion.CASCADE, to='alcohol.alcol_code')),
                ('region_code', models.ForeignKey(db_column='region_code', on_delete=django.db.models.deletion.CASCADE, to='alcohol.region_code')),
            ],
            options={
                'db_table': 'alcohol',
            },
        ),
        migrations.CreateModel(
            name='Alchol_recom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweet', models.IntegerField()),
                ('sour', models.IntegerField()),
                ('scent', models.IntegerField()),
                ('body', models.IntegerField()),
                ('abv', models.IntegerField()),
                ('score', models.IntegerField(default=0, null=True)),
                ('alco_no', models.ForeignKey(db_column='alco_no', on_delete=django.db.models.deletion.CASCADE, to='alcohol.alcohol')),
            ],
        ),
    ]
