# Generated by Django 4.1.1 on 2022-09-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alchol_recom',
            new_name='Alcohol_recom',
        ),
        migrations.AlterModelTable(
            name='alcohol_recom',
            table='alcohol_recom',
        ),
    ]
