# Generated by Django 4.1.1 on 2022-09-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0002_rename_alchol_recom_alcohol_recom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alcohol_recom',
            old_name='abv',
            new_name='abv_level',
        ),
    ]
