# Generated by Django 4.1.1 on 2022-09-26 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0003_rename_abv_alcohol_recom_abv_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alcohol_recom',
            name='id',
        ),
        migrations.AlterField(
            model_name='alcohol_recom',
            name='alco_no',
            field=models.ForeignKey(db_column='alco_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='alcohol.alcohol'),
        ),
    ]
