# Generated by Django 4.1.1 on 2022-09-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0004_remove_alcohol_recom_id_alter_alcohol_recom_alco_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcohol',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='tags',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
