# Generated by Django 4.1.1 on 2022-09-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0005_alcohol_size_alter_alcohol_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='alco_img',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
