# Generated by Django 4.1.1 on 2022-09-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0006_alter_alcohol_alco_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='food',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
