# Generated by Django 4.1.1 on 2022-09-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0008_alter_alcohol_award_alter_alcohol_brewery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='award',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='food',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
