# Generated by Django 4.1.1 on 2022-09-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0009_alter_alcohol_award_alter_alcohol_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alcohol',
            name='alco_img',
        ),
    ]
