# Generated by Django 4.1.1 on 2022-09-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0010_remove_alcohol_alco_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='like_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alcohol_recom',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
