# Generated by Django 4.1.1 on 2022-09-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0011_alter_alcohol_like_cnt_alter_alcohol_recom_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol_recommend',
            fields=[
                ('alcohol_no', models.ForeignKey(db_column='alcohol_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='alcohol.alcohol')),
                ('sweet', models.IntegerField()),
                ('sour', models.IntegerField()),
                ('scent', models.IntegerField()),
                ('body', models.IntegerField()),
                ('abv_level', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'alcohol_recommend',
            },
        ),
        migrations.RenameModel(
            old_name='Alcol_code',
            new_name='Alcohol_code',
        ),
        migrations.RenameField(
            model_name='alcohol',
            old_name='alco_name',
            new_name='alcohol_name',
        ),
        migrations.RenameField(
            model_name='alcohol',
            old_name='alco_no',
            new_name='alcohol_no',
        ),
        migrations.RenameField(
            model_name='alcohol',
            old_name='like_cnt',
            new_name='like_count',
        ),
        migrations.RenameField(
            model_name='alcohol',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='alcohol_code',
            old_name='alco_code',
            new_name='alcohol_code',
        ),
        migrations.RenameField(
            model_name='alcohol_code',
            old_name='alco_type',
            new_name='alcohol_type',
        ),
        migrations.RemoveField(
            model_name='alcohol',
            name='alco_code',
        ),
        migrations.AddField(
            model_name='alcohol',
            name='alcohol_code',
            field=models.ForeignKey(db_column='alcohol_code', default='A1', on_delete=django.db.models.deletion.CASCADE, to='alcohol.alcohol_code'),
        ),
        migrations.AlterModelTable(
            name='alcohol_code',
            table='alcohol_code',
        ),
        migrations.DeleteModel(
            name='Alcohol_recom',
        ),
    ]
