# Generated by Django 4.1.1 on 2022-09-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0013_alter_alcohol_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='like_count',
            field=models.IntegerField(null=True),
        ),
    ]
