# Generated by Django 4.1.1 on 2022-10-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0015_alter_alcohol_recommend_alcohol_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alcohol_recommend',
            old_name='score',
            new_name='score1',
        ),
        migrations.AddField(
            model_name='alcohol_recommend',
            name='score2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alcohol_recommend',
            name='score3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alcohol_recommend',
            name='score4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
