# Generated by Django 4.1.1 on 2022-10-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0016_rename_score_alcohol_recommend_score1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcohol_recommend',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
