# Generated by Django 4.1.1 on 2022-10-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0019_alcohol_score4_alcohol_score3_alcohol_score2'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcohol_recommend',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
